version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=revolut
      - POSTGRES_PASSWORD=revolut
      - POSTGRES_DB=revolut
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakPassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./keycloak-data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8180:8180"
    command: [ "-Djboss.socket.binding.port-offset=100" ]
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakPassword
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    depends_on:
      - mysql
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
  revolut:
    build:
      context: revolut/
    container_name: revolut
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/revolut
      - SPRING_DATASOURCE_USERNAME=revolut
      - SPRING_DATASOURCE_PASSWORD=revolut
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_CONVERSION-SERVICE=http://bourse:8082
      - KEYCLOAK.AUTH-SERVER-URL=http://keycloak:8180/auth
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
  bourse-service:
    build:
      context: bourse-service/
    container_name: bourse-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
  client-service:
    build:
      context: client-service/
    container_name: client-service
    environment :
      - APP_REVOLUT=http://revolut:8080
    depends_on:
      - revolut
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
volumes:
  data:
  keycloak-data:
  imports: